name: FlexUnit

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: joshtynjala/setup-adobe-air-action@v2
        with:
          air-version: "51.1"
          accept-license: true
      - name: Install dependencies
        run: |
          wget -O flexunit.zip http://mirrors.ibiblio.org/apache/flex/flexunit/4.2.0/binaries/apache-flex-flexunit-4.2.0-4.12.0-bin.zip
          unzip -q flexunit.zip
          rm flexunit/flexunit-4.2.0-20140410-flex_4.12.0.swc
      - name: Compile AIR application
        run: |
          amxmlc -debug --source-path+=src --library-path+=flexunit --output bin/GithubActionsFlexUnitExample.swf src/TestMain.as
          cp GithubActionsFlexUnitExample-app.xml bin/GithubActionsFlexUnitExample-app.xml
      - name: Run Tests
        working-directory: bin
        run: adl GithubActionsFlexUnitExample-app.xml
